[package]
name = "generate_inserts"
version = "1.0.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
random_name_generator = { workspace = true }
rand = { workspace = true  }
